# Generated by Django 3.2.5 on 2021-07-24 02:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150, null=True, unique=True, verbose_name='Award Name')),
                ('earned_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Earned On')),
            ],
            options={
                'verbose_name': 'Award',
                'verbose_name_plural': 'Awards',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150, null=True, unique=True, verbose_name='Island Name')),
                ('email', models.CharField(blank=True, default='', max_length=256, null=True, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, null=True, unique=True, verbose_name='Phone Number')),
                ('awards', models.ManyToManyField(blank=True, help_text='List of all the Users assigned to this Team.', related_name='user_team', related_query_name='user_teams', to='chapter_1.Award', verbose_name='Assigned Users')),
                ('users', models.ManyToManyField(blank=True, help_text='List of all the Users assigned to this Team.', related_name='user_team', related_query_name='user_teams', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Users')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
    ]
